### ISSUE TITLE
Clarify difference between Peer.send() and Network.send()

### ISSUE THREAD

**Issue by cjdelisle** [coast-team/netflux#10]
As far as I can tell from the spec, `Peer.send(string)` does the same thing as `Network.send(Peer, string)`. If they are indeed the same, perhaps `Network.broadcast()` should be renamed to `Network.send()` so one can think of a Network and a Peer as comparable items.

**Comment by kalitine** [comment]
I think you are right. It is unnecessary redundancy which may mislead API users. I'll change it.
