### ISSUE TITLE
Consider usage of Uint8Array in message send/onMessage functions

### ISSUE THREAD

**Issue by cjdelisle** [coast-team/netflux#12]
In order to be able to encrypt data which is sent over the network, it is best that the send functions accept Uint8Array as opposed to only string. For my needs it is ok to only transfer Uint8Array and not accept or return strings.
If others require to send/accept strings, one might convert strings to Uint8Arrays when send() is called and add a parameter to onMessage() which specifies whether the callback would like the type converted to a string or kept as a Uint8Array.

**Comment by cjdelisle** [comment]
It seems typed arrays are well supported in the browser ecosystem: http://caniuse.com/#feat=typedarrays

**Comment by kalitine** [comment]
Good idea. With the next commit we will be able to send data as ArrayBuffer, Int8Array, Uint8Array, Uint8ClampedArray, Int16Array, Uint16Array, Int32Array, Uint32Array, Float32Array, Float64Array, DataView

**Comment by cjdelisle** [comment]
I think we only need to support Uint8Array but that looks great anyway.
