### ISSUE TITLE
Reception of splited messages

### ISSUE THREAD

**Issue by Conaclos** [coast-team/netflux#14]
Hi!
# Context
- 6 or more computers
- Sending of large messages (1000 characters or more)
# Observation

The message is received as a spited message into several ones.
Therefore the parsed JSON is partial.
This is lead to two type of exceptions:
- JSON syntax error
- JSON token error
# Hypothesis

A WebRTC message is divided into separate chunks (See [Chromium issue 2270](https://bugs.chromium.org/p/webrtc/issues/detail?id=2270)).

The delay between some chunk is too large and then several messages are produced upon reception.
# Fix ideas
- Check if SCTP provides a configuration to ensure message recovering from separate chunks
- Switch to TCP (implies performance reduction)
- Implement a custom buffer

**Comment by oster** [comment]
According to discussions from [Chromium issue 2270](https://bugs.chromium.org/p/webrtc/issues/detail?id=2270) and after some very basic tests. It seems the size limit of a message is 64k (maximum size of the buffer in SCTP).

One can reproduce this issue by sending a document of 64k characters. (javascript:"0123456789".repeat(6400))

**Comment by Conaclos** [comment]
An interesting reading about chunk and chunk sending:

http://viblast.com/blog/2015/2/25/webrtc-bufferedamount/
