### ISSUE TITLE
WebSocket.close(code) don't pass the code in the CloseEvent

### ISSUE THREAD

**Issue by MarcDelp** [coast-team/netflux#17]
There is a problem when closing a connection to a WebSocket with a custom code in Node JS.

The signaling servers I'm using are the one online at ws://sigver-coastteam.rhcloud.com:8000 and the one in the SigVer Chrome Application.

The results are identical : the CloseEvent fired when the socket is closed doesn't have the right code.

For example, in case there are 2 WebSockets opened, sending the same key to the server to initiate a channel, the second is closed with code 1000 whereas the signaling server used `socket.closed(4002, 'Key already exists')`.

**Comment by kalitine** [comment]
Problem solved, as now Netflux & Signaling server use uWebSocket library.
