### ISSUE TITLE
Upgrade wrtc dependency version

### ISSUE THREAD

**Issue by oster** [coast-team/netflux#20]
Please update the wrtc dependency to "0.0.61" as the "0.0.60" failed to build on OSX (10.12.1).

**Comment by kalitine** [comment]
It's a little bit complected for now. As for example Ubuntu 16.04 (and it seems to be the same for some other Linux distributions) 0.0.61 failed on run time and the only solution I've found in wrtc repo is to build from source the whole library which will take a very significant time. I prefer to wait for the next release hoping they will resolve this issue.

**Comment by oster** [comment]
I understand.
Does this issue was reported to wrtc project? 
I mean, I try to install wrtc@0.061 on a fresh ubuntu:16.04 and I was able to run successfully their tests suites. So maybe they are not aware of your issue.

**Comment by kalitine** [comment]
It is know issue: https://github.com/js-platform/node-webrtc/issues/281
Solution here: https://github.com/js-platform/node-webrtc/wiki/Building
On my Ubuntu 16.04 GNOME for wrtc `npm test` I have this issue:
`undefined symbol: XOpenDisplay`
and it is the same for Netflux tests.

**Comment by kalitine** [comment]
I've moved wrtc dependency from _optional_ to _peer_. Thus it accelerates install time and leaves the API consumer to install its own version which works for him.
