### ISSUE TITLE
Use of ECMA 2015

### ISSUE THREAD

**Issue by cjdelisle** [coast-team/netflux#4]
I notice that the preliminary javascript is written in ECMA2015 language, at XWiki we are standardized on ECMA 5 and we have no plans of changing that in the near future. I suppose there is no harm if the WebRTC implementation is developed in ECMA2015 but it is very important to us that the API allows us to develop using standard ECMA 5 Javascript.

**Comment by MichaelBailly** [comment]
It will, it's transpiled, using babel, to ES5 code.

**Comment by cjdelisle** [comment]
My main concern is that trying to call into the API from our own Javascript we end up in a similar situation to calling C++ from C code ( http://stackoverflow.com/questions/12371370/using-c-mangled-functions-from-c ) and then we need to write an API shim in ES5 so then the actual API we're calling is not the one which was specified.

**Comment by MichaelBailly** [comment]
This won't happen. Javascript ES5=>ES2015 is not comparable to C=>C++.

**Comment by cjdelisle** [comment]
Ok I will take your word for it.
