### ISSUE TITLE
Facade.onBroadcastMessage() looks like a DoS issue.

### ISSUE THREAD

**Issue by cjdelisle** [coast-team/netflux#7]
Generally in networking we don't want to allow someone to send a message which will go to _everyone_, with a concept of channels or multicast groups, one can PART (exit) a channel/group and then they will nolonger be sent the messages intended for that group. I'm curious about the reasoning for `Facade.onBroadcastMessage()` which if I understand properly is global.

**Comment by kalitine** [comment]
One of the `Facade.onBroadcastMessage` parameter is `Network`. You may think of `Network` as a room where peers share one or several documents on which they are collaborating together. Thus this method will be used to receive document modification from other peers.

While peer is editing a document the API sends his modifications to all peers who are working on the same document (thus they are in the same network), but NOT TO ALL NETWORKS.

Is that is that is what you were talking?

**Comment by cjdelisle** [comment]
Right, I misread it, I'll consider this then a duplicate of #8
